### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by scoult3r** [notro/spi-bcm2708#3]
How would one go from a vanilla raspbian installation on a raspberry pi 2, to an application making (for example) 100 byte writes/reads through SPI?

[This](https://github.com/notro/rpi-source/wiki/Examples-on-how-to-build-various-modules#dma-capable-spi-master-driver-spi-bcm2708) page describes building the module, are they standalone instructions or do I need to follow [this](https://github.com/notro/rpi-source/wiki) first?

Once its installed [this](https://github.com/notro/spi-bcm2708/wiki) page indicates that the driver can not be used from userspace? How can I get an userspace application to take advantage of DMA SPI? Do i need to write a kernel module that can be called by userspace programs or what?

Sorry for being a noob.

**Comment by notro** [comment]
Install and run rpi-source first, then follow the example.
Here's a prebuilt kernel with that driver: https://github.com/notro/fbtft/wiki#install

I believe spi-bcm2835 driver will allow SPI DMA from userspace shortly: https://github.com/raspberrypi/linux/issues/1036
But not directly, the buffer will be copied by the spidev driver before it's sent using DMA

100 bytes is just on the edge of when you benefit from DMA though, see commit message: https://github.com/torvalds/linux/commit/3ecd37edaa2a6ba3246e2c35714be9316b1087fe

**Comment by scoult3r** [comment]
I understand,

Thanks so much!
